import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogOutBtn from "./LogOutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  let res = cookies().get("mode");

  return (
    <html lang="en">
      <body className={res.value == "dark" ? "dark-mode" : ""}>
        <div className="navbar">
          <Link href="/" className="logo">
            AppleBoard
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">write</Link>
          {session ? (
            <span>
              {session.user.name} <LogOutBtn />{" "}
            </span>
          ) : (
            <LoginBtn></LoginBtn>
          )}
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
